/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConnecting: typeof import('./src/components/AppConnecting.vue')['default']
    AssetDetails: typeof import('./src/components/assets/AssetDetails.vue')['default']
    AssetDropZone: typeof import('./src/components/assets/AssetDropZone.vue')['default']
    AssetFontPreview: typeof import('./src/components/assets/AssetFontPreview.vue')['default']
    AssetGridItem: typeof import('./src/components/assets/AssetGridItem.vue')['default']
    AssetListItem: typeof import('./src/components/assets/AssetListItem.vue')['default']
    AssetPreview: typeof import('./src/components/assets/AssetPreview.vue')['default']
    CodeSnippets: typeof import('./src/components/code/CodeSnippets.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    CustomTabComponent: typeof import('./src/components/CustomTabComponent.vue')['default']
    DevToolsLogo: typeof import('./src/components/common/DevToolsLogo.vue')['default']
    DockingPanel: typeof import('./src/components/common/DockingPanel.vue')['default']
    EmptyPane: typeof import('./src/components/common/EmptyPane.vue')['default']
    ExpandIcon: typeof import('./src/components/common/ExpandIcon.vue')['default']
    FilepathItem: typeof import('./src/components/assets/FilepathItem.vue')['default']
    GraphDrawer: typeof import('./src/components/graph/GraphDrawer.vue')['default']
    GraphFileType: typeof import('./src/components/graph/GraphFileType.vue')['default']
    GraphNavbar: typeof import('./src/components/graph/GraphNavbar.vue')['default']
    IconTitle: typeof import('./src/components/common/IconTitle.vue')['default']
    IframeView: typeof import('./src/components/common/IframeView.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    PanelGrids: typeof import('./src/components/common/PanelGrids.vue')['default']
    RouteMetaDetail: typeof import('./src/components/pages/RouteMetaDetail.vue')['default']
    RoutePathItem: typeof import('./src/components/pages/RoutePathItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesTable: typeof import('./src/components/pages/RoutesTable.vue')['default']
    SectionBlock: typeof import('./src/components/common/SectionBlock.vue')['default']
    SFCView: typeof import('./src/components/common/SFCView.vue')['default']
    SideNav: typeof import('./src/components/common/SideNav.vue')['default']
    SideNavItem: typeof import('./src/components/common/SideNavItem.vue')['default']
    SplitScreen: typeof import('./src/components/common/SplitScreen.vue')['default']
    TabIcon: typeof import('./src/components/common/TabIcon.vue')['default']
    TabsGrid: typeof import('./src/components/common/TabsGrid.vue')['default']
    TimelineLayers: typeof import('./src/components/timeline/TimelineLayers.vue')['default']
    ViewModeSwitch: typeof import('./src/components/chrome/ViewModeSwitch.vue')['default']
    WaitForConnection: typeof import('./src/components/WaitForConnection.vue')['default']
  }
}
